#!/usr/bin/env bash

# shellcheck disable=SC2145
# shellcheck disable=SC2068

set -e -o pipefail

source /usr/local/share/gamesync/gamesync-utilities

log "Syncing saves before executing $@"

log "Loading variables in ~/.gamesync"

# Load environment variables from the file
while IFS='=' read -r key value; do
    export "$key"="$value"
done < ~/.gamesync

# shellcheck disable=SC2154
log "Steam app id: ${SteamAppId}"

if [[ -z ${SteamAppId} ]]; then
  SteamAppId="0"
fi

log "Checking if syncthing is running"

check_syncthing "${SYNCTHING_API}" "${SYNCTHING_URL}" "${SYNCTHING_FOLDER_ID}"

log "Syncthing is up"

set +e +o pipefail

log "executing game!"

eval 'env LD_PRELOAD="${LD_PRELOAD}" $@'

log "done!"
