#!/usr/bin/env bash

log() {
  local content
  local datetime
  local log_line
  content="$1"
  datetime="$(date +'%Y-%m-%d %H:%M:%S')"
  log_line="${datetime}|${content}"
  echo "$log_line" >> ~/.local/share/gamesync/logs/log.log
}

check_syncthing() {
  local SYNCTHING_API="$1"
  local SYNCTHING_URL="$2"
  local SYNCTHING_FOLDER_ID="$3"
  local TIMEOUT=10
  local start_time
  start_time=$(date +%s)
  local endpoint
  endpoint="${SYNCTHING_URL}/rest/db/completion?folder=${SYNCTHING_FOLDER_ID}"

  log "Attempting to ping ${endpoint}"

  while true; do
    local response
    response=$(curl -s -H "X-API-Key: ${SYNCTHING_API}" -X GET "${endpoint}")

    if [[ ${response} = "no such folder" ]]; then
      log "The SYNCTHING_FOLDER_ID ${SYNCTHING_FOLDER_ID} does not exist! Did you forget to set it up?"
      exit 4
    fi

    local sync_status
    sync_status=$(echo "${response}" | grep -o '"completion": [0-9]*\(\.[0-9]\+\)\?' | cut -d ' ' -f 2)

    if [[ -z "${sync_status}" ]]; then
      log "Error retrieving status from ${endpoint}"
      exit 2
    fi

    if [[ "${sync_status}" = "Not Authorized" ]]; then
      log "Invalid API key used"
      exit 3
    fi

    if [ "${sync_status}" = "100" ]; then
      log "Folder is completely synchronized."
      break
    fi

    local current_time
    current_time=$(date +%s)
    local elapsed_time=$((current_time - start_time))
    if [ $elapsed_time -ge $TIMEOUT ]; then
      log "Timeout reached. Folder synchronization did not complete."
      exit 5
    fi

    sleep 1
  done
}

